### ISSUE TITLE
Add build for arm64 linux.

### ISSUE THREAD

**Issue by zorg-bessarab** [aquasecurity/traceeshark#38]
Could you please add release for arm64 linux for those, who are testing on their rpi's and QEMU linux vm's on Mac?

**Comment by oshaked1** [comment]
Hi, it will be a few days until I can add an automated build for Linux ARM64 and publish a new release. In the meantime, I can manually build it for you and add it to the latest release, would that be good for you?

Keep in mind that releases target specific Wireshark versions, the automated builds currently target 3.6.2 (Ubuntu 22.04 package version), 4.2.2 (Ubuntu 24.04 package version) and 4.2.6 (latest). If you are using a distro with a different package version I can also add it to the automated builds.

**Comment by oshaked1** [comment]
I added builds for Linux ARM64 and they are available in the latest release. Let me know if they are good for you or you need a release for a different Wireshark version.
